site_name: 'Backstage POC'
site_description: 'Main documentation for Backstage features and framework APIs'
repo_url: https://github.com/UdayKunta/my-node-app1
edit_uri: edit/master/docs

theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
  locale: en
  analytics: {gtag: 'G-274394082'}
  highlightjs: true

nav:
  - Home: index.md
  
plugins:
  - techdocs-core
