site_name: 'Backstage POC'
site_description: 'Main documentation for Backstage features and framework APIs'
repo_url: https://github.com/UdayKunta/my-node-app1
edit_uri: edit/master/docs

plugins:
  - techdocs-core
